version: "3.0"

services:
  lab:
    image: "jupyter/datascience-notebook"    
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work